version: '3.4'

services:
  eternallaurels:
    image: eternallaurels
    build:
      context: eternal-laurels
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
