import Image from "next/image";

function Citymap(props){
  return (
    <div class='absolute w-[180%] h-[160%] -left-[30%] -top-[calc(80/3%)]'>
      <Image
        src='/./general/ciudad.png'
        alt='fondo'
        layout='fill'
        name='ciudad'
      />
      <map name='ciudad'>
        <area 
          id='1'
          shape='rect'
          coords='0,0,100,100'
        >
        </area>
        <area 
          id='2'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'
        />
        <area 
          id='3'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'
        />
        <area
          id='4'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'
        />
        <area
          id='5'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'
        />
        <area 
          id='6'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'        />
        <area 
          id='7'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'
        />
        <area 
          id='8'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'
        />
        <area 
          id='9'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'
        />
        <area
          id='10'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'
        />
        <area
          id='11'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'
        />
        <area
          id='12'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'
        />
        <area
          id='13'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'
        />
        <area
          id='14'
          shape='rect'
          coords=''
          class='bg-[url("/img/ejemplo.png")]'
        />
      </map>
    </div>
  );
}

export default Citymap;